// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Salmon.Data;

#nullable disable

namespace Salmon.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231003103703_first")]
    partial class first
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Salmon.Models.Cookiestand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Owner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("average_cookies_per_sale")
                        .HasColumnType("float");

                    b.Property<int>("maximum_customers_per_hour")
                        .HasColumnType("int");

                    b.Property<int>("minimum_customers_per_hour")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Cookiestands");
                });

            modelBuilder.Entity("Salmon.Models.HourlySale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CookieStandId")
                        .HasColumnType("int");

                    b.Property<int>("SalesValue")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CookieStandId");

                    b.ToTable("HourlySale");
                });

            modelBuilder.Entity("Salmon.Models.HourlySale", b =>
                {
                    b.HasOne("Salmon.Models.Cookiestand", "CookieStand")
                        .WithMany("HourlySales")
                        .HasForeignKey("CookieStandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CookieStand");
                });

            modelBuilder.Entity("Salmon.Models.Cookiestand", b =>
                {
                    b.Navigation("HourlySales");
                });
#pragma warning restore 612, 618
        }
    }
}
